export const APPLY_HOMELOAN = "APPLY_HOMELOAN";
export const GET_HOMELOAN = "GET_HOMELOAN";
export const APPLY_EDUCATIONLOAN = "APPLY_EDUCATIONLOAN";
export const GET_EDUCATIONLOAN = "GET_EDUCATIONLOAN";
